import Head from "next/head";
import Main from "../components/Main";
import About from "../components/About";
import Skill from "../components/Skill";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Faisal | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
      <About />
      <Skill />
      <Projects />
      <Contact />
      <Footer />
    </div>
  );
}
